Updated minio images, add cronjob to set expiry to minio errors buckets
sighupio/fury-kubernetes-logging pull request #118
Opened 2023-01-31 15:01 UTC by nutellinoit

As per title.

This change is needed to expire old errors like we expire logs on elasticsearch after a set time.

2023-01-31 15:12 UTC, ralgozino requested changes
minor nitpicks.

Can we document somewhere about these expiring rules (I guess in the `operated` readme)?

2023-01-31 15:12 UTC, ralgozino commented on katalog/logging-operated/minio/cronjob.yaml
> +# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
```suggestion
# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
```

2023-01-31 15:12 UTC, ralgozino commented on katalog/logging-operated/minio/cronjob.yaml
> +  schedule: "0 * * * *"
missing new line

2023-02-06 14:29 UTC, nutellinoit commented
> Can we document somewhere about these expiring rules (I guess in the `operated` readme)?

Yes!

2023-02-07 08:48 UTC, ralgozino approved these changes
LGTM! 🚢

2023-02-07 08:50 UTC, merged