[FEATURE] - replace elasticsearch with opensearch
sighupio/fury-kubernetes-logging pull request #67
Opened 2022-03-03 10:08 UTC by nutellinoit

Hi team, i'm working on the elasticsearch/opensearch replacement

This change is needed due to the licensing change from Elasticsearch.

Here a simple list of what I need to do before cosindering this PR ready:

- [x] Check Opensearch licensing
- [x] Opensearch single package
- [x] Opensearch triple package
- [x] Opensearch dashboard package
- [x] Cerebro settings
- [x] ~Curator settings~
- [x] Copy images to registry.sighup.io and patch resources accordingly
- [x] Fine tune requests and limits
- [x] Enable alerting
- [x] Wait for logging operator 2.0.0 release
- [x] Change Readme accordingly
- [x] Add single package READMEs
- [x] remove security plugin on opensearch-dashboards 
- [x] Adapt ci/cd tests
- [x] update opensearch to 2.0.0 ⚠️ 
- [x] Replace curator with ISM policies
- [x] Write release notes with informations on how to migrate to the new stack

2022-06-06 16:02 UTC, ralgozino requested changes
Overall looks pretty good! some minor suggestions.

Two additional questions:
1. testing the single instance OpenSearch Cerebro is in yellow with a warning on 3 unassigned shards. To solve this, can we configure the single replica deployment out of the box? You also get an alert triggered by the yellow status once you add the metrics port to the service.
2. Should we consider adding some grafana dashboard being that we have prometheus metrics available?

2022-06-06 16:29 UTC, nutellinoit commented on README.md
> +The central piece of the stack is the CNCF certified open source search engine [opensearch][opensearch-page], combined
Mmmh, you are right

2022-06-06 16:30 UTC, nutellinoit commented on README.md
> +    version: "v3.0.0"
A random kibana was forgotten

2022-06-06 16:30 UTC, nutellinoit commented on README.md
Yes, I need to update the logo

2022-06-06 16:32 UTC, nutellinoit commented on docs/COMPATIBILITY_MATRIX.md
> +| vUnreleased                         |                    |                    |                    |                    |                    |                    |                    | :white_check
This PR is pointed to `next` branch, i will do a final PR from `next` to `master` before the 3.0.0 release

2022-06-06 16:32 UTC, nutellinoit commented on katalog/opensearch-dashboards/README.md
> +[example](../../examples/opensearch-dashboard-node-selector).
I need to remove this reference

2022-06-06 16:35 UTC, nutellinoit commented on katalog/opensearch-single/README.md
> +[opensearch-rules]: https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
Yep, you are right

2022-06-06 16:38 UTC, nutellinoit commented on katalog/configs/events/output.yml
> +    ssl_verify: false
It's a leftover from the "opensearch with auth" tests

2022-06-06 16:38 UTC, nutellinoit commented on katalog/configs/ingress-nginx/output.yml
> +    ssl_verify: false
It's a leftover from the "opensearch with auth" tests

2022-06-06 16:38 UTC, nutellinoit commented on katalog/configs/kubernetes/cluster-output.yml
> +    ssl_verify: false
It's a leftover from the "opensearch with auth" tests

2022-06-06 16:38 UTC, nutellinoit commented on katalog/configs/systemd/common/output.yml
> +    ssl_verify: false
It's a leftover from the "opensearch with auth" tests

2022-06-06 16:40 UTC, nutellinoit commented on katalog/configs/events/output.yml
> +    ssl_verify: false
It's OK, by default the fluentd opensearch plugin has ssl_verify true even if the target is in http, actually breaking the log output

2022-06-06 16:40 UTC, nutellinoit commented on katalog/configs/systemd/common/output.yml
> +    ssl_verify: false
It's OK, by default the fluentd opensearch plugin has ssl_verify true even if the target is in http, actually breaking the log output

2022-06-07 07:47 UTC, nutellinoit commented on katalog/opensearch-single/rules.yml
>            expr: elasticsearch_cluster_health_status{color="red"} == 1
Me too

2022-06-07 09:09 UTC, nutellinoit commented on katalog/opensearch-dashboards/MAINTENANCE.md
> +
Added some more infos

2022-06-07 09:23 UTC, ralgozino commented on README.md
sounds good to me :)

2022-06-07 09:27 UTC, nutellinoit commented
> 1. testing the single instance OpenSearch Cerebro is in yellow with a warning on 3 unassigned shards. To solve this, can we configure the single replica deployment out of the box? You also get an alert triggered by the yellow status once you add the metrics port to the service.

The single deployment is not production grade, it is correct that there are unassigned shards

> 2. Should we consider adding some grafana dashboard being that we have prometheus metrics available?

Maybe in the future, right now we use Cerebro to "monitor" the cluster status

2022-06-07 10:24 UTC, ralgozino commented
> > 1. testing the single instance OpenSearch Cerebro is in yellow with a warning on 3 unassigned shards. To solve this, can we configure the single replica deployment out of the box? You also get an alert triggered by the yellow status once you add the metrics port to the service.
> 
> The single deployment is not production grade, it is correct that there are unassigned shards

Make sense, can we add something in the main readme in the package description and in the package's readme warning this? For example, in the package description in the main readme: "Not intended for production use"; and in the readme a similar notice.

> > 2. Should we consider adding some grafana dashboard being that we have prometheus metrics available?
> 
> Maybe in the future, right now we use Cerebro to "monitor" the cluster status

👍

2022-06-07 10:44 UTC, ralgozino requested changes
some minor tweaks, we are really close 💪

2022-06-07 10:44 UTC, ralgozino commented on katalog/opensearch-single/README.md
> +
```suggestion

> ⚠️ Please note that the OpenSearch Single variant is not intended for production use. Please use [opensearch-triple](../opensearch-triple), the high-availability version, for production.

```

2022-06-07 10:44 UTC, ralgozino commented on katalog/opensearch-single/README.md
> +
```suggestion

> ℹ️ when using the OpenSearch single variant, the cluster will be in `YELLOW` state because of the single replica.

```

2022-06-07 10:44 UTC, ralgozino commented on katalog/opensearch-triple/README.md
> +* Elasticsearch documentation: [Elasticsearch Homepage][es-doc]
```suggestion
* OpenSearch image: `opensearchproject/opensearch:1.2.4`
* OpenSearch repo: [OpenSearch on Github][opensearch-gh]
* OpenSearch documentation: [OpenSearch Homepage][opensearch-doc]
```

2022-06-07 10:44 UTC, ralgozino commented on katalog/opensearch-triple/README.md
> +Fury distribution OpenSearch Single is deployed with the following configuration:
```suggestion
OpenSearch Triple is deployed with the following configuration:
```

2022-06-07 10:44 UTC, ralgozino commented on katalog/opensearch-triple/README.md
> +- Only a single OpenSearch node can be deployed on each node of the cluster
```suggestion
- OpenSearch nodes running in different Kubernetes nodes
```

2022-06-07 10:44 UTC, ralgozino commented on katalog/opensearch-triple/README.md
> +- Prometheus exporter to expose Opensearch metrics
```suggestion
- Prometheus exporter to expose OpenSearch metrics
```

2022-06-07 12:54 UTC, ralgozino approved these changes
LGTM 🚀

2022-06-07 12:56 UTC, ralgozino commented on katalog/opensearch-triple/README.md
> +> [`opensearch-single](../opensearch-single/README.md#alerts) to read
```suggestion
> [opensearch-single](../opensearch-single/README.md#alerts) to read
```

2022-06-07 12:56 UTC, merged